# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

# Mod
mod_version=1.1.0
maven_group=sunbatheproductions28.guardribbits
mod_id=guardribbits
archives_name=guardribbits
enabled_platforms=fabric,forge,neoforge,quilt

# Minecraft
minecraft_version=26.2

# Loaders
fabric_loader_version=0.19.5
fabric_api_version=0.160.0+26.2
quilt_loader_version=0.31.0-beta.4
neoforge_version=26.2.0.87
forge_version=26.2-65.1.3

# Dependencies
geckolib_version=5.5.5
ribbits_version=4.2.0
